name: Publish Node.js Package

on:
  release:
    types: [created]

jobs:

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Get code access
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies 
        run: npm ci

      - name: Build Package
        run: npm run build
        
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}